<?php
    $multistr0 = array('zh-tw'=>'康橋國際學校幼兒園（林口校區）耗材管理系統', 'en'=>'Kang Chiao International School Preschool (Linkou Campus) Supplies Management System');
    $multistr1 = array('zh-tw'=>'耗材檢視', 'en'=>'Supplies Checking');
    $multistr2 = array('zh-tw'=>'耗材剩餘', 'en'=>'Remaining Supplies');
    $multistr3 = array('zh-tw'=>'申請檢視', 'en'=>'Applying Conditions');
    $multistr4 = array('zh-tw'=>'借用明細', 'en'=>'Applying Details');
    $multistr5 = array('zh-tw'=>'進貨明細', 'en'=>'Purchase Details');
    $multistr6 = array('zh-tw'=>'耗材管理', 'en'=>'Supplies Management');
    $multistr7 = array('zh-tw'=>'新增耗材', 'en'=>'Increase Supply');
    $multistr8 = array('zh-tw'=>'修改耗材', 'en'=>'Modify Supply');
    $multistr9 = array('zh-tw'=>'人員管理', 'en'=>'User Management');
    $multistr10 = array('zh-tw'=>'新增使用者', 'en'=>'Create User');
    $multistr11 = array('zh-tw'=>'修改使用者', 'en'=>'Modify User');
    $multistr20 = array('zh-tw'=>'重設密碼', 'en'=>'Reset Password');
    $multistr21 = array('zh-tw'=>'開始新學期', 'en'=>'New Semester');
    $multistr12 = array('zh-tw'=>'個人資料', 'en'=>'Personal Information');
    $multistr13 = array('zh-tw'=>'修改密碼', 'en'=>'Change Password');
    $multistr14 = array('zh-tw'=>'登出', 'en'=>'Log out');
    $multistr15 = array('zh-tw'=>'借用上限', 'en'=>'Applying Limit');
    $multistr16 = array('zh-tw'=>'申請耗材', 'en'=>'Apply Supplies');
    $multistr17 = array('zh-tw'=>'審核申請', 'en'=>'Review Apply');
    $multistr18 = array('zh-tw'=>'歸還耗材', 'en'=>'Return Supplies');
    $multistr19 = array('zh-tw'=>'歷史紀錄', 'en'=>'Applying Record');
    $smulti0 = array('zh-tw'=>'耗材選擇', 'en'=>'Supplies Selection');
    $smulti1 = array('zh-tw'=>'全選', 'en'=>'Select All');
    $smulti2 = array('zh-tw'=>'開始日期', 'en'=>'Start Date');
    $smulti3 = array('zh-tw'=>'結束日期', 'en'=>'End Date');
    $mc = array('zh-tw'=>'主分類', 'en'=>'Main Category');
    $sc = array('zh-tw'=>'次分類', 'en'=>'Sub Category');
    $iname = array('zh-tw'=>'品名', 'en'=>'Item');
    $size = array('zh-tw'=>'規格', 'en'=>'Specification');
    $color = array('zh-tw'=>'顏色', 'en'=>'Color');
    $unit = array('zh-tw'=>'單位', 'en'=>'Unit');
    $com = array('zh-tw'=>'廠商', 'en'=>'Brand');
    $adt = array('zh-tw'=>'申請日期', 'en'=>'Applying Date');
    $class = array('zh-tw'=>'班級', 'en'=>'Class');
    $aq = array('zh-tw'=>'借用量', 'en'=>'Applying Quantity');
    $submit = array('zh-tw'=>'提交', 'en'=>'Submit');
    $role = array('zh-tw'=>'角色', 'en'=>'Role');
    $re = array('zh-tw'=>'剩餘量', 'en'=>'Remaining');
    $acc = array('zh-tw'=>'尚可申請量', 'en'=>'Self Remain Quantity');
    $orq = array('zh-tw'=>'欲申請量', 'en'=>'Applying Quantity');
    $ar = array('zh-tw'=>'申請理由', 'en'=>'Applying Reason');
    $oar = array('zh-tw'=>'其他申請理由', 'en'=>'Other Applying Reason');
    $ruser = array('zh-tw'=>'借用者', 'en'=>'Username');
    $get1 = array('zh-tw'=>'領取狀態', 'en'=>'Get');
    $ret1 = array('zh-tw'=>'歸還狀態', 'en'=>'Return');
    $username = array('zh-tw'=>'姓名', 'en'=>'Name');
    $account = array('zh-tw'=>'帳號', 'en'=>'Account');
    $get2 = array('zh-tw'=>'已領取', 'en'=>'Received');
    $rev = array('zh-tw'=>'審核通過', 'en'=>'Passed Review');
    $cancel = array('zh-tw'=>'取消申請', 'en'=>'Cancel Apply');
    $oldPassword = array('zh-tw'=>'舊密碼', 'en'=>'Old Password');
    $newPassword = array('zh-tw'=>'新密碼', 'en'=>'New Password');
    $passwordAgain = array('zh-tw'=>'再次確認', 'en'=>'Password Again');
    $num = array('zh-tw'=>'數量', 'en'=>'Quantity');
    $il = array('zh-tw'=>'預設申請上限', 'en'=>'Default Applying Limit');
    $pdt = array('zh-tw'=>'進貨日期', 'en'=>'Purchase Date');
    $con = array('zh-tw'=>'總消耗', 'en'=>'Consumption');
    $ret2 = array('zh-tw'=>'可歸還', 'en'=>'Returnable');
    $export = array('zh-tw'=>'輸出耗材總表', 'en'=>'Export csv');
    $pos = array('zh-tw'=>'位置', 'en'=>'Location');
    $newp = array('zh-tw'=>'新進耗材', 'en'=>'New Purchase Supply');
    $ret3 = array('zh-tw'=>'已歸還', 'en'=>'Returned');
    $an = array('zh-tw'=>'新增數量', 'en'=>'Record Purchase');
    $qis = array('zh-tw'=>'找不到想要的品項或規格嗎？', 'en'=>'Cannot find the supply you want?');
    $login_failed = array('zh-tw'=>'登入失敗!', 'en'=>'Login Failed!');
    $password = array('zh-tw'=>'密碼', 'en'=>'Password');
    $login = array('zh-tw'=>'登入', 'en'=>'Login');
    $forgot_password = array('zh-tw'=>'忘記密碼？', 'en'=>'Forget passward?');
    $rstate = array('zh-tw'=>'審核狀態', 'en'=>'Review State');
    $wrev = array('zh-tw'=>'待審核', 'en'=>'Waiting for Review');
    $edit = array('zh-tw'=>'操作', 'en'=>'Edit');
    $vc = array('zh-tw'=>'檢視類別', 'en'=>'Perspective');
    $vc1 = array('zh-tw'=>'老師申請', 'en'=>'As Teacher');
    $vc2 = array('zh-tw'=>'各班申請', 'en'=>'As Class');
    $vc3 = array('zh-tw'=>'活動申請', 'en'=>'As Activity');
    $vd = array('zh-tw'=>'類別細項', 'en'=>'Perspective Details');
    $cc = array('zh-tw'=>'新增情形', 'en'=>'Create Conditions');
    $cc1 = array('zh-tw'=>'已知主分類和次分類', 'en'=>'Known Main & Sub-Category');
    $cc2 = array('zh-tw'=>'已知主分類但沒有次分類', 'en'=>'Known Main Category, No Sub-Category');
    $cc3 = array('zh-tw'=>'沒有主分類和次分類', 'en'=>'No Main & Sub-Category');
    $ce1 = array('zh-tw'=>'[警告]: 這是一個影響資料的選項，請慎選!', 'en'=>'[Caution]: This option affects data directly, please select carefully!');
    $chinese = array('zh-tw'=>'中文', 'en'=>'Mandarin');
    $english = array('zh-tw'=>'英文', 'en'=>'English');
    $ii = array('zh-tw'=>'產品資訊', 'en'=>'Item Information');
    $intr = array('zh-tw'=>'須歸還的品項', 'en'=>'Returnable Item');
    $semester = array('zh-tw'=>'學期', 'en'=>'Semester');
    $nse1 = array('zh-tw'=>'[警告]: 不可逆操作，請謹慎使用!', 'en'=>'[Caution]: Irreversible Action!');
?>